### ISSUE TITLE
[FE] Login Page Error Message

### ISSUE THREAD

**Issue by rocity** [sbenemerito/instaz#40] opened 2019-07-23 22:56 UTC
Error message showing `HTML` code.

![image](https://i.imgur.com/luoW01I.png)

**Comment by mhasan09** [comment] 2022-05-01 21:46
Still having this error

**Comment by sbenemerito** [comment] 2022-05-07 05:55
It's been about 3 years... my bad on this one 😂

It isn't exactly a 'bug', and we never expect the API to return HTML, hence the weird error message display. This was caused by `REACT_APP_API_URL` not being defined for frontend. This made the React client incorrectly make GET/POST requests to it's same domain, and not the API's (`localhost:8000` by default).

My bad for leaving that out in the README. Fixed in https://github.com/sbenemerito/instaz/pull/59
Closing this issue because https://github.com/sbenemerito/instaz#1-set-environment-variables-1 should solve it :+1:

**Closed by sbenemerito** 2022-05-07 05:55 UTC
